---
- name: install apt key for docker
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: create docker deb file from template
  become: yes
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list

- name: install pip
  become: yes
  apt: name=python-pip state=present update_cache=yes

- name: install pip packages
  become: yes
  pip: name={{ item }} state=present
  with_items:
    - docker_py
    - docker-compose

- name: install predocker packages
  become: yes
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - apparmor
    - python-yaml

- name: install linux extras for kernel
  become: yes
  apt: name=linux-image-extra-{{ ansible_kernel }} state=latest

- name: install docker
  become: yes
  apt: name=docker-engine state=present update_cache=yes

- name: add group docker
  become: yes
  group: name=docker state=present

- name: add docker group to ubuntu user
  become: yes
  user: name={{ansible_env.USER}} append=yes groups=docker

- name: enable docker
  become: yes
  service: name=docker enabled=yes

- name: Install docker compose
  become: yes
  shell: curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

- file: path=/usr/local/bin/docker-compose mode="u=rwx,go=rx"
  become: yes


- name: start docker
  become: yes
  service: name=docker state=started



