---
- name: install apt key for docker
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: create docker deb file from template
  become: yes
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list

- name: install pip
  become: yes
  apt: name=python-pip state=present update_cache=yesq

- name: install docker py
  become: yes
  pip: name=docker_py state=present

- name: install predocker packages
  become: yes
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: install linux extras for kernel
  become: yes
  apt: name=linux-image-extra-{{ ansible_kernel }} state=latest

- name: install docker
  become: yes
  apt: name=docker-engine state=present update_cache=yes

- name: add group docker
  become: yes
  group: name=docker state=present

- name: add docker group to ubuntu user
  become: yes
  user: name={{ansible_env.USER}} append=yes groups=docker

- name: enable docker
  become: yes
  service: name=docker enabled=yes

- name: start docker
  become: yes
  service: name=docker state=started



