---
- name: update ubuntu
  become: yes
  apt: upgrade=dist update_cache=yes

- name: install some packages
  become: yes
  apt: name={{ item }} state=present
  with_items: "{{ packages_to_install }}"